import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BackgroundContainer from '@/components/Background';
import FooterContainer from '@/components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="w-full min-h-full">
      <body className={`${inter.className} flex items-center justify-center m-0 p-0 w-full min-h-full`}>
        <div className="max-w-screen-xl h-screen mx-auto p-0 text-center">
          <BackgroundContainer />
          {children}
          <FooterContainer />
        </div>
      </body>
    </html>
  );
}
